apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: flex-set
spec:
  template:
    metadata:
      name: flex-deploy
      labels:
        app: flex-deploy
    spec:
      containers:
        - image: pharmer/flexvolumes:canary
          imagePullPolicy: Always
          name: flex-deploy
          securityContext:
              privileged: true
          volumeMounts:
            - mountPath: /flexmnt
              name: flexvolume-mount
            - name: flexvolume-secret
              mountPath: /flexsecret
          env:
            - name: PROVIDER
              value: digitalocean
      volumes:
        - name: flexvolume-mount
          hostPath:
            path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
        - name: flexvolume-secret
          hostPath:
            path: /var/run/secrets/pharmer/flexvolmues